#!/usr/bin/env python
import os.path
import tidy, sys, pycurl, cStringIO
from Ft.Xml.Domlette import NonvalidatingReader
from Ft.Xml.XPath.Context import Context
from Ft.Xml.XPath import Compile, Evaluate
from Ft.Xml.Xslt.Processor import Processor
from Ft.Xml.InputSource import DefaultFactory
XHTML_NS = "http://www.w3.org/1999/xhtml"

HEADERS = ['User-agent: Mozilla/4.0 (compatible; MSIE 5.5; Windows NT)', 'Accept-Language: en-us,en;q=0.5']
COOKIEFILE = '/home/stef/.config/munchr/cookies.lwp'
FORMTEMPLATE = '/home/stef/tasks/other/munchr/formscan.xsl'

ERROR_EXPR = Compile('string(//h:div[@class="simplebox error"]/text())')

login="https://www.liberit.hu/tiki/tiki-login.php"
user="stef"
password="password"
loginparams = [('user', user), ('pass', password)]

#testitem="http://www.liberit.hu/tiki/tiki-view_tracker.php"
#testitem="file:///home/stef/tasks/other/munchr/form.html"
testitem="http://www.google.com/"

def run(action,params):
   print >> sys.stderr, 'sending action'   
   c = pycurl.Curl()
   b = cStringIO.StringIO()
   c.setopt(pycurl.URL, action)
   c.setopt(pycurl.HTTPHEADER, HEADERS)
   c.setopt(pycurl.WRITEFUNCTION, b.write)
   c.setopt(pycurl.HTTPPOST, params)
   c.setopt(pycurl.FOLLOWLOCATION, 1)
   c.setopt(pycurl.SSL_VERIFYPEER, 0)
   c.setopt(pycurl.MAXREDIRS, 5)
   c.setopt(pycurl.COOKIEFILE, COOKIEFILE)
   c.setopt(pycurl.COOKIEJAR, COOKIEFILE)
   c.perform()
   c.close
   raw=b.getvalue()

   # tidy to xhtml
   print >> sys.stderr, 'cleaning response'   
   options = dict(output_xhtml=1, add_xml_decl=0, indent=0, tidy_mark=0, doctype="strict", wrap=0)
   xhtml=str(tidy.parseString(raw, **options))
   # make it a 4suite document
   print >> sys.stderr, 'checking errors'   
   doc = NonvalidatingReader.parseString(xhtml,action)
   context = Context(doc, processorNss={"h": XHTML_NS})
   #Compute the XPath against the context
   error=ERROR_EXPR.evaluate(context)
   print >> sys.stderr, 'done', action
   return (error, xhtml)

def scan(url):
   print >> sys.stderr, 'setting up http connection to', url
   c = pycurl.Curl()
   b = cStringIO.StringIO()
   c.setopt(pycurl.URL, url)
   c.setopt(pycurl.HTTPHEADER, HEADERS)
   c.setopt(pycurl.WRITEFUNCTION, b.write)
   c.setopt(pycurl.FOLLOWLOCATION, 1)
   c.setopt(pycurl.SSL_VERIFYPEER, 0)
   c.setopt(pycurl.MAXREDIRS, 5)
   c.setopt(pycurl.COOKIEFILE, COOKIEFILE)
   c.setopt(pycurl.COOKIEJAR, COOKIEFILE)
   c.perform()
   c.close
   raw=b.getvalue()

   # tidy to xhtml
   print >> sys.stderr, 'cleaning response'   
   options = dict(output_xhtml=1, add_xml_decl=0, indent=0, tidy_mark=0, doctype="strict", wrap=0)
   xhtml=str(tidy.parseString(raw, **options))

   print >> sys.stderr, 'scanning forms'
   xsltproc = Processor()
   xsltproc.appendStylesheet(DefaultFactory.fromUri(FORMTEMPLATE))
   forms = xsltproc.run(DefaultFactory.fromString(xhtml,url))

   print >> sys.stderr, 'done'
   return forms

#print run(login,loginparams)[0]
print scan(testitem)
