#!/usr/bin/env python
#     Copyright (C) 2008  Stefan Marsiske
# 
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
import getopt, sys, yaml
from workr import fetch, VERSION

DEBUG=None
NOPOST=None

def usage():
   print "feedr", VERSION
   print "usage: feedr [--debug] [--nopost] [<actionfiles>]"
   print ""
   print "actions can be either supplied via stdin or files"

if(__name__=="__main__"):
   # handling of options
   try:
      opts, args = getopt.getopt(sys.argv[1:], "hdn", ["help","debug","nopost"])
   except getopt.GetoptError:
      usage()
      sys.exit(2)
   for o, a in opts:
      if o in ("-h","--help"):
         usage()
         sys.exit()
      if o in ("-d","--debug"):
         DEBUG=1
      if o in ("-n","--nopost"):
         NOPOST=1
   if(len(args)>0):
      # process each url specified 
      for action in args:
         sys.stderr.write("processing "+action+'\n')
         try:
            params = yaml.load(file(action, 'r'))
         except yaml.YAMLError, exc:
            print "Error in configuration file:", exc
            sys.exit(1)
   else:
      # we need to process stdin
      if(DEBUG): sys.stderr.write("processing stdin\n")
      try:
         params = yaml.load(sys.stdin.read())
      except yaml.YAMLError, exc:
         print "Error in configuration file:", exc
         sys.exit(1)
   results,xhtml=fetch(params,debug=DEBUG,nopost=NOPOST)
   for res in results:
      print res
   if(DEBUG): sys.stderr.write(xhtml)
