#!/usr/bin/env python
import getopt, sys, yaml
from workr import fetch, VERSION

DEBUG=None
NOPOST=None

def usage():
   print "feedr", VERSION
   print "usage: feedr [--debug] [--nopost] [<actionfiles>]"
   print ""
   print "actions can be either supplied via stdin or files"

if(__name__=="__main__"):
   # handling of options
   try:
      opts, args = getopt.getopt(sys.argv[1:], "hdn", ["help","debug","nopost"])
   except getopt.GetoptError:
      usage()
      sys.exit(2)
   for o, a in opts:
      if o in ("-h","--help"):
         usage()
         sys.exit()
      if o in ("-d","--debug"):
         DEBUG=1
      if o in ("-n","--nopost"):
         NOPOST=1
   if(len(args)>0):
      # process each url specified 
      for action in args:
         sys.stderr.write("processing "+action+'\n')
         try:
            params = yaml.load(file(action, 'r'))
         except yaml.YAMLError, exc:
            print "Error in configuration file:", exc
            sys.exit(1)
   else:
      # we need to process stdin
      if(DEBUG): sys.stderr.write("processing stdin\n")
      try:
         params = yaml.load(sys.stdin.read())
      except yaml.YAMLError, exc:
         print "Error in configuration file:", exc
         sys.exit(1)
   results,xhtml=fetch(params,debug=DEBUG,nopost=NOPOST)
   for res in results:
      print res
   if(DEBUG): sys.stderr.write(xhtml)
