#!/usr/bin/env python
# vim: set fileencoding=utf8

import pygtk,sys
pygtk.require('2.0')
import gtk

COL_TEXT = 0

LABEL="title"
LABEL2="_description"

class CompletedEntry(gtk.Entry):
    def __init__(self):
        gtk.Entry.__init__(self)
        completion = gtk.EntryCompletion()
        completion.set_match_func(self.match_func)
        completion.connect("match-selected",
                            self.on_completion_match)
        completion.set_model(gtk.ListStore(str))
        completion.set_text_column(COL_TEXT)
        self.set_completion(completion)

    def match_func(self, completion, key, iter):
        model = completion.get_model()
        return model[iter][COL_TEXT].startswith(self.get_text())

    def on_completion_match(self, completion, model, iter):
        self.set_text(model[iter][COL_TEXT])
        self.set_position(-1)

    def add_words(self, words):
        model = self.get_completion().get_model()
        for word in words:
            model.append([word])

    def enter_callback(self, widget, entry):
       print entry.get_text()
       sys.exit(0)

if __name__ == "__main__":
   #win=gtk.Window(gtk.WINDOW_TOPLEVEL)
   win=gtk.Dialog("gaskr",flags=gtk.DIALOG_NO_SEPARATOR)
   win.set_size_request(400, 45)
   win.set_title("gaskr")
   win.set_position(gtk.WIN_POS_CENTER_ALWAYS)
   win.action_area.set_homogeneous(False)
   win.connect('delete-event', gtk.main_quit)

   hbox1=gtk.HBox()
   win.vbox.pack_start(hbox1,False,False,0)
   hbox2=gtk.HBox()
   win.vbox.pack_start(hbox2,False,False,0)

   label = gtk.Label(LABEL)
   label.set_alignment(xalign=1, yalign=0.5) 
   hbox1.pack_start(label, False, False, 0)

   entry = CompletedEntry()
   entry.add_words([u'ötlet',u'mérföldkő',u'sprint',u'beruházás',u'fejlesztés',u'szervezés',u'javítás',u'egyéb feladat'])
   entry.connect("activate", entry.enter_callback, entry)
   entry.set_size_request(349,20)
   hbox1.pack_start(entry, True, True, 0)

   button = gtk.Button()
   label = gtk.Label()
   label.set_text_with_mnemonic(LABEL2)
   label.set_alignment(xalign=1, yalign=0.5) 
   hbox2.pack_start(label, False, False, 0)

   #entry = CompletedEntry()
   #entry.add_words([u'ötlet',u'mérföldkő',u'sprint',u'beruházás',u'fejlesztés',u'szervezés',u'javítás',u'egyéb feladat'])
   #entry.connect("activate", entry.enter_callback, entry)
   #entry.set_size_request(349,20)
   #hbox2.pack_start(entry, True, True, 0)

   win.show_all()
   gtk.main()
