#!/bin/ksh
# Sample events script for mcabber, for use with dzen
#
# MiKael, 2005-07-15
# Stefan Marsiske <stefan.marsiske@gmail.com>, 2008

# $1 is the event type (MSG, STATUS)
# $2 for messages is IN, OUT
# $3 is the jid
# $4 is an optional filename (with the message contents)

event=$1
arg1=$2
arg2=$3
filename=$4
# Note that the 4th argument is only provided for incoming messages
# and when 'event_log_files' is set.

[[ $event == "MSG" ]] && [[ $arg1 = "IN" ]] && {
   [[ -n "$filename" ]]  && [[ -f "$filename" ]] && {
     # We could process filename here...
     . $HOME/.munchrrc
     (printf "^tw()^fg(red)${arg2}:^fg()"; cat $filename) >$DZENFEED
     /bin/rm $filename
  }
}
