#!/bin/ksh
# Sample events script for mcabber, for use with dzen
#
# MiKael, 2005-07-15
#     Copyright (C) 2008  Stefan Marsiske
# 
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# $1 is the event type (MSG, STATUS)
# $2 for messages is IN, OUT
# $3 is the jid
# $4 is an optional filename (with the message contents)

# The following sound comes with the gtkboard package,
# you can modify this line to play another one...
CMD_MSG_IN="/usr/bin/aplay /usr/share/sounds/KDE_Notify.wav"


event=$1
arg1=$2
arg2=$3
filename=$4
# Note that the 4th argument is only provided for incoming messages
# and when 'event_log_files' is set.

[[ $event == "MSG" ]] && [[ $arg1 = "IN" ]] && {
   [[ -n "$filename" ]]  && [[ -f "$filename" ]] && {
     # We could process filename here...
     . $HOME/.munchrrc
     (printf "^tw()^fg(red)${arg2}:^fg()"; cat $filename) >$DZENFEED
     $CMD_MSG_IN > /dev/null 2>&1
     /bin/rm $filename
  }
}
