#!/bin/ksh
#     Copyright (C) 2008  Stefan Marsiske
# 
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

[[ ! -r ~/.munchrrc ]] && cp doc/munchrrc ~/.munchrrc

. ~/.munchrrc || exit 1

# automagic create if not existing
[[ ! -d "$BASE" ]] && mkdir -p "$BASE"
# behold, automagic again ...
[[ ! -p "$DZENFEED" ]] && mkfifo "$DZENFEED"
# yet more... you guessed it: automagic
[[ ! -r "$RSSLIST" ]] && printf "http://yompb.wordpress.com/feed/\nhttp://rss.slashdot.org/Slashdot/slashdot" >"$RSSLIST"
# let's do some more automagic
[[ ! -d "$RSSCACHE" ]] && mkdir -p "$RSSCACHE"
